package com.ants.monitor.dao.mapper;

import com.ants.monitor.bean.entity.SysUserDO;

public interface SysUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int insert(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    SysUserDO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserDO record);
}