package com.ants.monitor.dao.mapper;

import java.util.List;

import com.ants.monitor.bean.entity.SysUserDO;

public interface SysUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int insert(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int insertSelective(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    SysUserDO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dubbo_sys_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserDO record);
    
    /**
     * 根据用户名查询用户
     * @param userName
     * @return
     */
    SysUserDO selectByUserName(String userName);
    
    /**
     * 根据条件查询用户列表
     * @param userName
     * @return
     */
    List<SysUserDO> selectList(SysUserDO user);
    
    /**
     * 根据条件查询用户个数
     * @param user
     * @return
     */
    int selectListCount(SysUserDO user);
}